source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'
# platform :ios, '9.0'

target 'IPAShrink' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IPAShrink

  pod 'SDWebImage'
  #install timeout ???!!!
  #pod 'iOS-WebP'
  
  target 'IPAShrinkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IPAShrinkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
